### ISSUE TITLE
Page 2

### ISSUE THREAD

**Issue by MaymoonaAlBoloshi** [MaymoonaAlBoloshi/stepper-form#11]
## Background
from page the user should be able to go to page 2

![image](https://github.com/user-attachments/assets/b2d12b1c-ef7a-4d7a-a5bf-c8ea5773c570)

- on clicking next on page one the user should be able to navigate to page 2
- A toggle component should be created separately, on which we should be able to select a single item as in the design
- ignore the switch bellow the select group
- the page should have the title and description as shown in the desing
- the page should have a next and a back button
- on clicking back the user should be sent back to page one 
- the stepper must update on changing steps which is shown in the design to indicate what step the user is on

**Comment by ireemalqarni** [comment]
Facing an issue where both Page 1 (Personal Info) and Page 2 (Plan Selection) appear simultaneously, and you are unable to move between these pages as expected. This behavior is preventing the form from functioning properly as a multi-step form with separate, navigable steps.

- Both Page 1 and Page 2 are being rendered at the same time, instead of each page being displayed one at a time based on the user's navigation actions.

- When users click the "Next Step" button on Page 1, they should be taken to Page 2 (Plan Selection). However, this transition is not happening, and the user remains on Page 1.

- After setting up routing, neither Page 1 nor Page 2 is being displayed. Instead, only the sidebar (or navigation menu) is visible, with the main content area remaining blank.

![Scr7](https://github.com/user-attachments/assets/a61547ee-dd9f-41e4-a51f-c786bfb0b36d)

**Comment by MaymoonaAlBoloshi** [comment]
@ireemalqarni  create a draft PR so i can take a look at the code

**Comment by MaymoonaAlBoloshi** [comment]
here is a hint on how to do this, look for React context API,  using the context API you can create global state, which means you can update the state and read the state from anywhere without passing props
- one you have to a useStep context to store the step number globally
- use the global state step number to render the current page
- if step is 1 render page one and so on

**Comment by MaymoonaAlBoloshi** [comment]
@ireemalqarni  what is the error in the console?

**Comment by ireemalqarni** [comment]
No routes matched location "/"
